targets = [ "//:dynamic-bitset" ]

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
version = "1.41.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-integer"
version = "1.41.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-move"
version = "1.41.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-throw_exception"
version = "1.41.0"

