manifest = "705530a86c200a662fc938bf087e9b089b82ac5dab02a9244f1240b5baf6de14"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-integer"
target = "//:integer"

[[dependency]]
package = "github.com/buckaroo-pm/boost-move"
target = "//:move"

[[dependency]]
package = "github.com/buckaroo-pm/boost-throw_exception"
target = "//:throw-exception"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "1.65.1" ]
revision = "306bfa59b6c7de6b2079d295b052a8d97a5248bf"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.65.1" ]
revision = "debf71b9eb1f3a4d6a3d2bed838520b2f6641841"

[lock."github.com/buckaroo-pm/boost-core"]
versions = [ "1.65.1" ]
revision = "558ea1c4a33ce1b788bb4d7f18c0e20939adf6b1"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.65.1" ]
revision = "3838f909c0f1c5b5a9c7c775c68b92234b450146"

[lock."github.com/buckaroo-pm/boost-exception"]
versions = [ "1.65.1" ]
revision = "8e6efa01d89422ae22eb0eac342e5359a93cf07a"

[lock."github.com/buckaroo-pm/boost-integer"]
versions = [ "1.65.1" ]
revision = "99f0383e703ecbc4ac6eda0c35c5a75bc42d4ca4"

[lock."github.com/buckaroo-pm/boost-move"]
versions = [ "1.65.1" ]
revision = "9257d861cbc483199c8c125f05c278fa0f3fa0cd"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.65.1" ]
revision = "1f0d010def9d751df46fc68fb59568c0d57aa957"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.65.1" ]
revision = "fb23e2cb271ddcc265cb630bd7e26083bad8d32a"

[lock."github.com/buckaroo-pm/boost-throw_exception"]
versions = [ "1.65.1" ]
revision = "99e8dff8c8b932ab7a29404ac363551a3bcc81c8"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.65.1" ]
revision = "73bbde0665120a5743454c4eb96c26de6a0c2a83"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.65.1" ]
revision = "526215de29e2e5f4d4a49805963d4c88a664c200"
