manifest = "68d750191299023376852aa5d0e411b64609aa1cd9fe9f1f79fa8e9390b2ec4d"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-integer"
target = "//:integer"

[[dependency]]
package = "github.com/buckaroo-pm/boost-move"
target = "//:move"

[[dependency]]
package = "github.com/buckaroo-pm/boost-throw_exception"
target = "//:throw-exception"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "1.64.0" ]
revision = "08b0e47f48604e35b686f387283cb08c35d5e634"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.64.0" ]
revision = "983cb0fffa4fdc70e893d631133ea120bdbbd7e2"

[lock."github.com/buckaroo-pm/boost-core"]
versions = [ "1.64.0" ]
revision = "34e2089f4946915687cae970d85977a392f8cb32"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.64.0" ]
revision = "ffba5b8f6cb006f7dbcce83b065d9c5eaafcb72a"

[lock."github.com/buckaroo-pm/boost-exception"]
versions = [ "1.64.0" ]
revision = "3830d08d723310a7a206fa532b34b875311f9e8b"

[lock."github.com/buckaroo-pm/boost-integer"]
versions = [ "1.64.0" ]
revision = "b7f6bac1ca30e186a6b07020432368f0b3affa1b"

[lock."github.com/buckaroo-pm/boost-move"]
versions = [ "1.64.0" ]
revision = "ab8a21df9c02b615d0b8c8d758f089ef86b27025"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.64.0" ]
revision = "502f9962d6046fdfb83c22ac245b85b59f14e101"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.64.0" ]
revision = "456ec3b6e6d6f9885496d443381fbc44f7061cbc"

[lock."github.com/buckaroo-pm/boost-throw_exception"]
versions = [ "1.64.0" ]
revision = "d15a7fde63af590a807593bac6d33a2c7f48a474"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.64.0" ]
revision = "bde9e46cc146e2f93017eb1a9068194239a45058"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.64.0" ]
revision = "d926c1817bb9c1f6e7b9cc353e937a9e10c56f4e"
